version: '2'
services:
    jhipsterstore-app:
        image: jhipsterstore
        external_links:
            - jhipsterstore-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jhipsterstore
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterstore-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterstore-postgresql
